# Generated by Django 4.1.3 on 2022-11-29 00:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="images/records/")),
            ],
        ),
        migrations.CreateModel(
            name="Trainer_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.FileField(upload_to="exerciseImg/")),
                ("f_area", models.TextField(max_length=100)),
                ("equipment", models.TextField(max_length=100)),
                ("prep", models.TextField(max_length=1000)),
                ("execution", models.TextField(max_length=1000)),
                ("keyTip", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[(2, "Female"), (1, "Male"), (3, "Other")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "activity_level",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("height", models.CharField(blank=True, max_length=4, null=True)),
                ("weight", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "target_weight",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "medical_conditions",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "username",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("view", models.IntegerField(blank=True, default=0, null=True)),
                ("link", models.CharField(max_length=1000, null=True)),
                ("image", models.ImageField(null=True, upload_to="blog/coverImg")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
