# Generated by Django 4.1.3 on 2023-04-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Sedentary"),
                            ("2", "Lightly active"),
                            ("3", "Moderatly active"),
                            ("4", "Very active"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("height", models.CharField(blank=True, max_length=4, null=True)),
                ("weight", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "main_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Loose Weight"),
                            ("2", "Build Muscels"),
                            ("3", "Keep Fit"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "medical_conditions",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "username",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
