# Generated by Django 4.1.3 on 2022-12-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="image",
            field=models.ImageField(null=True, upload_to="Blogs/Cover Images"),
        ),
        migrations.AlterField(
            model_name="trainer_form",
            name="image",
            field=models.FileField(upload_to="Exercise Images/"),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(2, "Female"), (3, "Other"), (1, "Male")],
                max_length=20,
                null=True,
            ),
        ),
    ]
