# Generated by Django 4.1.3 on 2023-04-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="age",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
