# Generated by Django 4.1.3 on 2022-12-06 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_alter_blogmodel_image_alter_trainer_form_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="username",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="record", name="video", field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
