# Generated by Django 4.1.3 on 2023-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_record_username_alter_record_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="video",
            field=models.FileField(upload_to="recorded_videos/"),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(2, "Female"), (1, "Male"), (3, "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
