# Generated by Django 4.1.3 on 2023-01-13 07:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_record_video_alter_userdata_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="video",
            field=models.FileField(upload_to=app.models.video_collection_path),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(3, "Other"), (2, "Female"), (1, "Male")],
                max_length=20,
                null=True,
            ),
        ),
    ]
