# Generated by Django 4.1.3 on 2023-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_userdetails_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lightly active", "Lightly active"),
                    ("Moderatly active", "Moderatly active"),
                    ("Sedentary", "Sedentary"),
                    ("Very active", "Very active"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="main_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Build Muscels", "Build Muscels"),
                    ("Keep Fit", "Keep Fit"),
                    ("Loose Weight", "Loose Weight"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
