# Generated by Django 4.1.3 on 2023-03-13 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_alter_record_video_alter_userdata_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Accuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "avg_accuracy",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=40, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
