# Generated by Django 4.1.3 on 2023-03-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_accuracy_date_alter_userdata_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accuracy",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.trainer_form",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
