# Generated by Django 4.1.3 on 2023-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userdata_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='activity_level',
            field=models.CharField(blank=True, choices=[(3, 'Moderatly active'), (2, 'Lightly active'), (1, 'Sedentary'), (4, 'Very active')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[(2, 'Female'), (3, 'Other'), (1, 'Male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='main_goal',
            field=models.CharField(blank=True, choices=[(2, 'Build Muscels'), (3, 'Keep Fit'), (1, 'Loose Weight')], max_length=20, null=True),
        ),
    ]
