# Generated by Django 4.1.3 on 2023-03-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_accuracy_exercise_alter_userdata_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accuracy",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(2, "Female"), (1, "Male"), (3, "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
